/* =============================================================================
 * Bangkok Rail Network — data
 * -----------------------------------------------------------------------------
 * Station orders and official station codes are taken from the operators' public
 * maps. Fares, operating hours and headways are INDICATIVE figures for planning;
 * always confirm against the official operator before you travel.
 *   BTS  — https://www.bts.co.th/eng/
 *   MRT  — https://metro.bemplc.co.th/?lang=en   (Blue & Purple, operated by BEM)
 *   MRT monorail (Yellow/Pink) — https://www.mrta.co.th/en/
 *   ARL  — https://www.srtet.co.th/en/
 *   SRT Red Line — https://www.srtet.co.th/  /  https://www.railway.co.th/
 * Last reviewed: 2026-06.
 * ===========================================================================*/

const NETWORK = {
  meta: {
    currency: "THB",
    reviewed: "June 2026",
    note:
      "Times and fares are indicative for journey planning. Confirm with the operator before travel.",
  },

  lines: [
    /* ----------------------------------------------------------------- BTS */
    {
      id: "sukhumvit",
      name: "BTS Sukhumvit Line",
      short: "Sukhumvit",
      color: "#5cb531",
      textOn: "#0b1a07",
      operator: "BTS (Bangkok Mass Transit System)",
      type: "Elevated heavy rail",
      hours: "06:00 – 24:00 daily",
      headway: "Peak ~2–4 min · Off-peak ~5–8 min",
      fare: { min: 17, max: 47, flat: false },
      fareNote: "Distance-based single-journey fare, 17–47 THB. Rabbit card stored value accepted.",
      url: "https://www.bts.co.th/eng/",
      stations: [
        { code: "N24", name: "Khu Khot" },
        { code: "N23", name: "Yaek Kor Por Aor" },
        { code: "N22", name: "Royal Thai Air Force Museum" },
        { code: "N21", name: "Bhumibol Adulyadej Hospital" },
        { code: "N20", name: "Saphan Mai" },
        { code: "N19", name: "Sai Yud" },
        { code: "N18", name: "Phahon Yothin 59" },
        { code: "N17", name: "Wat Phra Sri Mahathat", x: ["pink"] },
        { code: "N16", name: "11th Infantry Regiment" },
        { code: "N15", name: "Bang Bua" },
        { code: "N14", name: "Royal Forest Department" },
        { code: "N13", name: "Kasetsart University" },
        { code: "N12", name: "Sena Nikhom" },
        { code: "N11", name: "Ratchayothin" },
        { code: "N10", name: "Phahon Yothin 24" },
        { code: "N9", name: "Ha Yaek Lat Phrao", x: ["blue"] },
        { code: "N8", name: "Mo Chit", x: ["blue"] },
        { code: "N7", name: "Saphan Khwai" },
        { code: "N5", name: "Ari" },
        { code: "N4", name: "Sanam Pao" },
        { code: "N3", name: "Victory Monument" },
        { code: "N2", name: "Phaya Thai", x: ["arl"] },
        { code: "N1", name: "Ratchathewi" },
        { code: "CEN", name: "Siam", x: ["silom"] },
        { code: "E1", name: "Chit Lom" },
        { code: "E2", name: "Phloen Chit" },
        { code: "E3", name: "Nana" },
        { code: "E4", name: "Asok", x: ["blue"] },
        { code: "E5", name: "Phrom Phong" },
        { code: "E6", name: "Thong Lo" },
        { code: "E7", name: "Ekkamai" },
        { code: "E8", name: "Phra Khanong" },
        { code: "E9", name: "On Nut" },
        { code: "E10", name: "Bang Chak" },
        { code: "E11", name: "Punnawithi" },
        { code: "E12", name: "Udom Suk" },
        { code: "E13", name: "Bang Na" },
        { code: "E14", name: "Bearing" },
        { code: "E15", name: "Samrong", x: ["yellow"] },
        { code: "E16", name: "Pu Chao" },
        { code: "E17", name: "Chang Erawan" },
        { code: "E18", name: "Royal Thai Naval Academy" },
        { code: "E19", name: "Pak Nam" },
        { code: "E20", name: "Srinagarindra" },
        { code: "E21", name: "Phraek Sa" },
        { code: "E22", name: "Sai Luat" },
        { code: "E23", name: "Kheha" },
      ],
    },

    {
      id: "silom",
      name: "BTS Silom Line",
      short: "Silom",
      color: "#0a7a3a",
      textOn: "#ffffff",
      operator: "BTS (Bangkok Mass Transit System)",
      type: "Elevated heavy rail",
      hours: "06:00 – 24:00 daily",
      headway: "Peak ~3–5 min · Off-peak ~6–8 min",
      fare: { min: 17, max: 47, flat: false },
      fareNote: "Distance-based single-journey fare, 17–47 THB. Rabbit card stored value accepted.",
      url: "https://www.bts.co.th/eng/",
      stations: [
        { code: "CEN", name: "Siam", x: ["sukhumvit"] },
        { code: "S1", name: "Ratchadamri" },
        { code: "S2", name: "Sala Daeng", x: ["blue"] },
        { code: "S3", name: "Chong Nonsi" },
        { code: "S4", name: "Saint Louis" },
        { code: "S5", name: "Surasak" },
        { code: "S6", name: "Saphan Taksin" },
        { code: "S7", name: "Krung Thon Buri", x: ["gold"] },
        { code: "S8", name: "Wongwian Yai" },
        { code: "S9", name: "Pho Nimit" },
        { code: "S10", name: "Talat Phlu" },
        { code: "S11", name: "Wutthakat" },
        { code: "S12", name: "Bang Wa", x: ["blue"] },
      ],
    },

    {
      id: "gold",
      name: "Gold Line",
      short: "Gold",
      color: "#c9a227",
      textOn: "#1a1405",
      operator: "BTS / Krungthep Thanakom",
      type: "Automated people mover (monorail-style)",
      hours: "06:00 – 24:00 daily",
      headway: "~5–8 min",
      fare: { min: 16, max: 16, flat: true },
      fareNote: "Flat fare 16 THB. Rabbit card accepted.",
      url: "https://www.bts.co.th/eng/",
      stations: [
        { code: "G1", name: "Krung Thon Buri", x: ["silom"] },
        { code: "G2", name: "Charoen Nakhon" },
        { code: "G3", name: "Khlong San" },
      ],
    },

    /* ----------------------------------------------------------------- MRT */
    {
      id: "blue",
      name: "MRT Blue Line",
      short: "Blue",
      color: "#1f4fa0",
      textOn: "#ffffff",
      operator: "MRT / BEM (Bangkok Expressway and Metro)",
      type: "Underground & elevated heavy rail (loop + branch)",
      hours: "06:00 – 24:00 daily",
      headway: "Peak ~3–5 min · Off-peak ~6–10 min",
      fare: { min: 17, max: 45, flat: false },
      fareNote: "Distance-based 17–45 THB. Through-fare with the Purple Line is capped at 70 THB.",
      url: "https://metro.bemplc.co.th/?lang=en",
      note: "Tha Phra is the junction where the city loop meets the Lak Song branch (codes BL01 & BL33).",
      stations: [
        { code: "BL01", name: "Tha Phra" },
        { code: "BL02", name: "Charan 13" },
        { code: "BL03", name: "Fai Chai" },
        { code: "BL04", name: "Bang Khun Non" },
        { code: "BL05", name: "Bang Yi Khan" },
        { code: "BL06", name: "Sirindhorn" },
        { code: "BL07", name: "Bang Phlat" },
        { code: "BL08", name: "Bang O" },
        { code: "BL09", name: "Bang Pho" },
        { code: "BL10", name: "Tao Poon", x: ["purple"] },
        { code: "BL11", name: "Bang Sue", x: ["redDark", "redLight"] },
        { code: "BL12", name: "Kamphaeng Phet" },
        { code: "BL13", name: "Chatuchak Park", x: ["sukhumvit"] },
        { code: "BL14", name: "Phahon Yothin", x: ["sukhumvit"] },
        { code: "BL15", name: "Lat Phrao", x: ["yellow"] },
        { code: "BL16", name: "Ratchadaphisek" },
        { code: "BL17", name: "Sutthisan" },
        { code: "BL18", name: "Huai Khwang" },
        { code: "BL19", name: "Thailand Cultural Centre" },
        { code: "BL20", name: "Phra Ram 9" },
        { code: "BL21", name: "Phetchaburi", x: ["arl"] },
        { code: "BL22", name: "Sukhumvit", x: ["sukhumvit"] },
        { code: "BL23", name: "Queen Sirikit National Convention Centre" },
        { code: "BL24", name: "Khlong Toei" },
        { code: "BL25", name: "Lumphini" },
        { code: "BL26", name: "Si Lom", x: ["silom"] },
        { code: "BL27", name: "Sam Yan" },
        { code: "BL28", name: "Hua Lamphong" },
        { code: "BL29", name: "Wat Mangkon" },
        { code: "BL30", name: "Sam Yot" },
        { code: "BL31", name: "Sanam Chai" },
        { code: "BL32", name: "Itsaraphap" },
        { code: "BL33", name: "Tha Phra (junction)" },
        { code: "BL34", name: "Bang Phai" },
        { code: "BL35", name: "Bang Wa", x: ["silom"] },
        { code: "BL36", name: "Phetkasem 48" },
        { code: "BL37", name: "Phasi Charoen" },
        { code: "BL38", name: "Bang Khae" },
        { code: "BL39", name: "Lak Song" },
      ],
    },

    {
      id: "purple",
      name: "MRT Purple Line",
      short: "Purple",
      color: "#7d3f98",
      textOn: "#ffffff",
      operator: "MRT / BEM (Bangkok Expressway and Metro)",
      type: "Elevated heavy rail",
      hours: "06:00 – 24:00 daily",
      headway: "Peak ~5–6 min · Off-peak ~8–10 min",
      fare: { min: 14, max: 42, flat: false },
      fareNote: "Distance-based 14–42 THB. Through-fare with the Blue Line is capped at 70 THB.",
      url: "https://metro.bemplc.co.th/?lang=en",
      stations: [
        { code: "PP01", name: "Khlong Bang Phai" },
        { code: "PP02", name: "Talad Bang Yai" },
        { code: "PP03", name: "Sam Yaek Bang Yai" },
        { code: "PP04", name: "Bang Phlu" },
        { code: "PP05", name: "Bang Rak Yai" },
        { code: "PP06", name: "Bang Rak Noi Tha It" },
        { code: "PP07", name: "Sai Ma" },
        { code: "PP08", name: "Phra Nang Klao Bridge" },
        { code: "PP09", name: "Yaek Nonthaburi 1" },
        { code: "PP10", name: "Bang Krasor" },
        { code: "PP11", name: "Nonthaburi Civic Center", x: ["pink"] },
        { code: "PP12", name: "Ministry of Public Health" },
        { code: "PP13", name: "Yaek Tiwanon" },
        { code: "PP14", name: "Wong Sawang" },
        { code: "PP15", name: "Bang Son" },
        { code: "PP16", name: "Tao Poon", x: ["blue"] },
      ],
    },

    {
      id: "yellow",
      name: "MRT Yellow Line",
      short: "Yellow",
      color: "#f6d100",
      textOn: "#1a1605",
      operator: "MRT / EBM (Eastern Bangkok Monorail)",
      type: "Straddle monorail",
      hours: "06:00 – 24:00 daily",
      headway: "Peak ~5 min · Off-peak ~10 min",
      fare: { min: 15, max: 45, flat: false },
      fareNote: "Distance-based 15–45 THB.",
      url: "https://www.mrta.co.th/en/",
      stations: [
        { code: "YL01", name: "Lat Phrao", x: ["blue"] },
        { code: "YL02", name: "Phawana" },
        { code: "YL03", name: "Chok Chai 4" },
        { code: "YL04", name: "Lat Phrao 71" },
        { code: "YL05", name: "Lat Phrao 83" },
        { code: "YL06", name: "Mahat Thai" },
        { code: "YL07", name: "Lat Phrao 101" },
        { code: "YL08", name: "Bang Kapi" },
        { code: "YL09", name: "Yaek Lam Sali" },
        { code: "YL10", name: "Si Kritha" },
        { code: "YL11", name: "Hua Mak", x: ["arl"] },
        { code: "YL12", name: "Kalantan" },
        { code: "YL13", name: "Si Nut" },
        { code: "YL14", name: "Srinagarindra 38" },
        { code: "YL15", name: "Suan Luang Rama IX" },
        { code: "YL16", name: "Si Iam" },
        { code: "YL17", name: "Si Udom" },
        { code: "YL18", name: "Si Nuch" },
        { code: "YL19", name: "Si Bearing" },
        { code: "YL20", name: "Si Dan" },
        { code: "YL21", name: "Si Thepha" },
        { code: "YL22", name: "Thipphawan" },
        { code: "YL23", name: "Samrong", x: ["sukhumvit"] },
      ],
    },

    {
      id: "pink",
      name: "MRT Pink Line",
      short: "Pink",
      color: "#e6007e",
      textOn: "#ffffff",
      operator: "MRT / NBM (Northern Bangkok Monorail)",
      type: "Straddle monorail",
      hours: "06:00 – 24:00 daily",
      headway: "Peak ~5 min · Off-peak ~10 min",
      fare: { min: 15, max: 45, flat: false },
      fareNote: "Distance-based 15–45 THB.",
      url: "https://www.mrta.co.th/en/",
      stations: [
        { code: "PK01", name: "Nonthaburi Civic Center", x: ["purple"] },
        { code: "PK02", name: "Khae Rai" },
        { code: "PK03", name: "Sanambin Nam" },
        { code: "PK04", name: "Samakkhi" },
        { code: "PK05", name: "Royal Irrigation Department" },
        { code: "PK06", name: "Yaek Pak Kret" },
        { code: "PK07", name: "Pak Kret Bypass" },
        { code: "PK08", name: "Chaeng Watthana–Pak Kret 28" },
        { code: "PK09", name: "Si Rat" },
        { code: "PK10", name: "Muang Thong Thani" },
        { code: "PK11", name: "Chaeng Watthana 14" },
        { code: "PK12", name: "Government Complex" },
        { code: "PK13", name: "National Telecom" },
        { code: "PK14", name: "Lak Si", x: ["redDark"] },
        { code: "PK15", name: "Rajabhat Phranakhon" },
        { code: "PK16", name: "Wat Phra Sri Mahathat", x: ["sukhumvit"] },
        { code: "PK17", name: "Ram Inthra 3" },
        { code: "PK18", name: "Lat Pla Khao" },
        { code: "PK19", name: "Ram Inthra Km.4" },
        { code: "PK20", name: "Maiyalap" },
        { code: "PK21", name: "Wat Phraya Suren" },
        { code: "PK22", name: "Ram Inthra Km.6" },
        { code: "PK23", name: "Khu Bon" },
        { code: "PK24", name: "Ram Inthra Km.9" },
        { code: "PK25", name: "Watcharaphon" },
        { code: "PK26", name: "Ram Inthra Km.11" },
        { code: "PK27", name: "Nopparat" },
        { code: "PK28", name: "Bang Chan" },
        { code: "PK29", name: "Setthabutbamphen" },
        { code: "PK30", name: "Min Buri" },
      ],
    },

    /* ----------------------------------------------------- Airport Rail Link */
    {
      id: "arl",
      name: "Airport Rail Link",
      short: "ARL",
      color: "#d2232a",
      textOn: "#ffffff",
      operator: "SRTET (State Railway of Thailand Electric Train)",
      type: "Elevated airport express / commuter",
      hours: "05:30 – 24:00 daily",
      headway: "Peak ~10 min · Off-peak ~12–15 min",
      fare: { min: 15, max: 45, flat: false },
      fareNote: "Distance-based 15–45 THB between Suvarnabhumi Airport and Phaya Thai.",
      url: "https://www.srtet.co.th/en/",
      stations: [
        { code: "A1", name: "Suvarnabhumi (Airport)" },
        { code: "A2", name: "Lat Krabang" },
        { code: "A3", name: "Ban Thap Chang" },
        { code: "A4", name: "Hua Mak", x: ["yellow"] },
        { code: "A5", name: "Ramkhamhaeng" },
        { code: "A6", name: "Makkasan", x: ["blue"] },
        { code: "A7", name: "Ratchaprarop" },
        { code: "A8", name: "Phaya Thai", x: ["sukhumvit"] },
      ],
    },

    /* -------------------------------------------------------- SRT Red Lines */
    {
      id: "redDark",
      name: "SRT Dark Red Line",
      short: "Dark Red",
      color: "#a31621",
      textOn: "#ffffff",
      operator: "SRTET (State Railway of Thailand Electric Train)",
      type: "Elevated & at-grade commuter rail",
      hours: "05:00 – 24:00 daily",
      headway: "Peak ~10–12 min · Off-peak ~15–20 min",
      fare: { min: 12, max: 42, flat: false },
      fareNote: "Distance-based 12–42 THB. Krung Thep Aphiwat is Thailand's main long-distance terminal.",
      url: "https://www.srtet.co.th/",
      stations: [
        { code: "RN01", name: "Krung Thep Aphiwat Central Terminal", x: ["blue", "redLight"] },
        { code: "RN02", name: "Chatuchak" },
        { code: "RN03", name: "Wat Samian Nari" },
        { code: "RN04", name: "Bang Khen" },
        { code: "RN05", name: "Thung Song Hong" },
        { code: "RN06", name: "Lak Si", x: ["pink"] },
        { code: "RN07", name: "Kan Kheha" },
        { code: "RN08", name: "Don Muang (Airport)" },
        { code: "RN09", name: "Lak Hok" },
        { code: "RN10", name: "Rangsit" },
      ],
    },

    {
      id: "redLight",
      name: "SRT Light Red Line",
      short: "Light Red",
      color: "#e8767c",
      textOn: "#2a0608",
      operator: "SRTET (State Railway of Thailand Electric Train)",
      type: "Elevated & at-grade commuter rail",
      hours: "05:00 – 24:00 daily",
      headway: "~15–20 min",
      fare: { min: 12, max: 42, flat: false },
      fareNote: "Distance-based 12–42 THB.",
      url: "https://www.srtet.co.th/",
      stations: [
        { code: "RW01", name: "Krung Thep Aphiwat Central Terminal", x: ["blue", "redDark"] },
        { code: "RW02", name: "Bang Son" },
        { code: "RW03", name: "Bang Bamru" },
        { code: "RW04", name: "Taling Chan" },
      ],
    },
  ],
};

/* Convenience lookup by id */
NETWORK.byId = NETWORK.lines.reduce((m, l) => ((m[l.id] = l), m), {});

if (typeof module !== "undefined") module.exports = NETWORK;
